const table = `create table detail(

    id_detail int not null , 
    id_master int not null ,
    nomor_aju varchar(255) not null , 
    kd_kelompok_pos varchar(255) ,	
    no_pos varchar(255) ,
    no_sub_pos varchar(255),	
    no_sub_sub_pos varchar(255),	
    no_master_blawb varchar(255) ,
    tgl_master_blawb date ,
    no_host_blawb varchar(255) ,	
    tgl_host_blawb date ,	
    mother_vessel varchar(255), 
    npwp_consignee varchar(255)	,
    nama_consignee varchar(255),
    alamat_consignee varchar(255),
    neg_consignee varchar(255),
    npwp_shipper varchar(255) ,	
    nama_shipper varchar(255) ,
    almt_shipper varchar(255),	
    neg_shipper varchar(255) ,	
    nama_notify varchar(255),
    almt_notify varchar(255) ,
    neg_notify varchar(255) ,
    pelabuhan_asal varchar(255),
    pelabuhan_transit varchar(255),
    pelabuhan_bongkar varchar(255),
    pelabuhan_akhir varchar(255),
    jumlah_kemasan int,
    jenis_kemasan varchar(255),
    merk_kemasan varchar(255) ,	
    jumlah_kontainer int,	
    bruto float	,
    volume float ,	
    fl_partial varchar(255) ,	
    total_kemasan int ,	
    total_kontainer int , 
    status_detail varchar(255),	
    fl_konsolidasi varchar(255), 
    fl_pecah varchar(255),	
    fl_perbaikan varchar(255),	
    jenis_id_shipper varchar(255),
    jenis_id_consignee varchar(255),
    primary key (id_detail) 
)`;
